#! /bin/bash
#
# dlfiles
# Copyright (C) 2013 Adrian Perez <aperez@igalia.com>
#
# Distributed under terms of the MIT license.
#

set -eu

if [[ $# -lt 1 || $# -gt 2 ]]; then
	echo "Usage: $0 branch [revision]" >&2
	exit 1
fi

branch=${1/\./_}
revision=${2:-HEAD}
svn_prefix="http://www.eglibc.org/svn/branches/eglibc-${branch}/libc"
svn_urls=(
	"${svn_prefix}/nss/nss_files/"
	"${svn_prefix}/resolv/mapv4v6addr.h"
	"${svn_prefix}/resolv/res_hconf.h"
)

for url in "${svn_urls[@]}"; do
	svn export --force -r "${revision}" "${url}"
done
mv nss_files/* ./
rmdir nss_files
